joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.125
    scale_linear_turbo:
      x: 0.2

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 1.0
    scale_angular_turbo:
      yaw: 1.5

    enable_button: 9 # Steam Deck LT
    enable_turbo_button: 10 # Steam Decl RT

    require_enable_button: true
