services:
  nanobot_core:
    image: nanobot:latest
    container_name: nanobot_dev
    runtime: nvidia
    network_mode: "host"
    restart: unless-stopped
    devices:
      - "/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_ABSCDOT3-if00-port0:/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_ABSCDOT3-if00-port0" # Dynamixel Controller
    device_cgroup_rules:
      - 'c 81:* rmw' # Allow all video devices
      - 'c 189:* rmw' # USB bus device class permissions
      - 'c 13:* rmw' # Allow all input devices
    volumes:
      - /dev:/dev:rshared
      - ./ros:/root/ros_ws/src/nanobot
      - /run/udev:/run/udev:ro