services:
  nanobot_core:
    image: nanobot:latest
    container_name: nanobot_dev
    runtime: nvidia
    network_mode: "host"
    restart: unless-stopped
    device_cgroup_rules:
      - 'c 81:* rmw' # Video
      - 'c 189:* rmw' # USB
      - 'c 13:* rmw' # Input
      - 'c 89:* rmw' # I2C
      - 'c 188:* rmw' # USB Serial
    volumes:
      - /dev:/dev:rshared
      - /run/udev:/run/udev:ro
      - ./ros:/root/ros_ws/src/nanobot
      - ./scripts:/root/ros_ws/scripts