/imu_filter:
  ros__parameters:
    fixed_frame: "imu_base_link"
    world_frame: "enu"
    use_mag: false
    # mag_bias_x: 4.081677922771673e-05
    # mag_bias_y: 5.844807692307692e-05
    # mag_bias_z: -6.847992979242978e-05