<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="nanobot">

  <!-- IMU specs -->
  <xacro:property name="imu_z_dim" value="0.002" />
  <xacro:property name="imu_body_z_offset" value="0.004" />
  
  <!-- Links and joints definition -->

  <joint name="imu_joint" type="fixed">
    <parent link="body_link" />
    <child link="imu_link" />
    <origin xyz="${body_x_dim/2} 0 ${body_z_dim - imu_body_z_offset - imu_z_dim}" rpy="${pi} 0 0" />
  </joint>

  <link name="imu_link" />

</robot>