<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="nanobot">

  <!-- LIDAR specs -->
  <xacro:property name="ldlidar_base_x_dim" value="0.039" />
  <xacro:property name="ldlidar_base_y_dim" value="0.039" />
  <xacro:property name="ldlidar_base_z_dim" value="0.0222" />
  
  <xacro:property name="ldlidar_link_height" value="0.0126" />
  <xacro:property name="ldlidar_link_radius" value="0.017645" />
  
  <xacro:property name="ldlidar_mass" value="0.047" />

  <!-- Links and joints definition -->

  <!-- Base -->

  <joint name="ldlidar_base_joint" type="fixed">
    <parent link="body_link" />
    <child link="ldlidar_base_link" />
    <origin xyz="${body_x_dim/2} 0 ${body_z_dim}" rpy="0 0 ${pi/2}" />
  </joint>

  <link name="ldlidar_base_link">
    <visual>
      <origin xyz="0 0 ${ldlidar_base_z_dim/2}" rpy="0 0 0" />
      <geometry>
        <box size="${ldlidar_base_x_dim} ${ldlidar_base_y_dim} ${ldlidar_base_z_dim}" />
      </geometry>
      <material name="red" />
    </visual>
    <collision>
      <origin xyz="0 0 ${ldlidar_base_z_dim/2}" rpy="0 0 0" />
      <geometry>
        <box size="${ldlidar_base_x_dim} ${ldlidar_base_y_dim} ${ldlidar_base_z_dim}" />
      </geometry>
    </collision>
    <xacro:inertial_box mass="${ldlidar_mass/2}" x="${ldlidar_base_x_dim}" y="${ldlidar_base_y_dim}"
      z="${ldlidar_base_z_dim}">
      <origin xyz="0 0 ${ldlidar_base_z_dim/2}" rpy="0 0 0" />
    </xacro:inertial_box>
  </link>

  <!-- Link -->

  <joint name="ldlidar_link_joint" type="fixed">
    <parent link="ldlidar_base_link" />
    <child link="ldlidar_link" />
    <origin xyz="0 0 ${ldlidar_base_z_dim + ldlidar_link_height/2}" rpy="0 0 0" />
  </joint>

  <link name="ldlidar_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder length="${ldlidar_link_height}" radius="${ldlidar_link_radius}" />
      </geometry>
      <material name="red" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder length="${ldlidar_link_height}" radius="${ldlidar_link_radius}" />
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${ldlidar_mass/2}" length="${ldlidar_link_height}" radius="${ldlidar_link_radius}">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:inertial_cylinder>
  </link>

  <!-- Gazebo -->

  <gazebo reference="ldlidar_link">
    <material>Gazebo/Red</material>

    <sensor name="laser" type="ray">
      <pose> 0 0 0 0 0 0 </pose>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <min_angle>-3.14</min_angle>
            <max_angle>3.14</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.02</min>
          <max>12</max>
        </range>
      </ray>
      <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <argument>~/out:=scan</argument>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>laser_frame</frame_name>
      </plugin>
    </sensor>
  </gazebo>
  
</robot>