<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="nanobot">

  <!-- <xacro:include filename="inertial_macros.xacro" /> -->

  <!-- LIDAR specs -->
  <xacro:property name="laser_beam_height" value="0.0285" />
  <xacro:property name="lidar_height" value="0.0348" />
  <xacro:property name="lidar_radius" value="0.017645" />
  <xacro:property name="lidar_mass" value="0.047" />

  <!-- Links and joints definition -->

  <joint name="laser_joint" type="fixed">
    <parent link="body_link" />
    <child link="laser_frame" />
    <origin xyz="${body_x_dim/2} 0 ${body_z_dim + laser_beam_height}" rpy="0 0 ${pi/2}" />
  </joint>

  <link name="laser_frame">
    <visual>
      <origin xyz="0 0 ${lidar_height/2 -laser_beam_height}" rpy="0 0 0" />
      <geometry>
        <cylinder length="${lidar_height}" radius="${lidar_radius}" />
      </geometry>
      <material name="red" />
    </visual>
    <collision>
      <origin xyz="0 0 ${lidar_height/2 -laser_beam_height}" rpy="0 0 0" />
      <geometry>
        <cylinder length="${lidar_height}" radius="${lidar_radius}" />
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${lidar_mass}" length="${lidar_height}" radius="${lidar_radius}">
      <origin xyz="0 0 ${lidar_height/2 -laser_beam_height}" rpy="0 0 0" />
    </xacro:inertial_cylinder>
  </link>

  <gazebo reference="laser_frame">
    <material>Gazebo/Red</material>

    <sensor name="laser" type="ray">
      <pose> 0 0 0 0 0 0 </pose>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <min_angle>-3.14</min_angle>
            <max_angle>3.14</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.02</min>
          <max>12</max>
        </range>
      </ray>
      <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <argument>~/out:=scan</argument>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>laser_frame</frame_name>
      </plugin>
    </sensor>
  </gazebo>
</robot>