version: '3'

services:
  ros2:
    container_name: ros2
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   USERNAME: 'nano'
    restart: always
    tty: true
    # user: 'nano'
    volumes:
      - ../:/home/nanobot
      - ${X11:-/dev/null}:${X11:-/.devnull}
      - ${KERNEL_MODULE:-/dev/null}:${KERNEL_MODULE:-/.devnull}
      - ${DEV_DRI:-/dev/null}:${DEV_DRI:-/.devnull}
      - ${DEV_SERIAL:-/dev/null}:${DEV_SERIAL:-/.devnull}
      - ${DEV_INPUT:-/dev/null}:${DEV_INPUT:-/.devnull}
    environment:
      DISPLAY: 'unix:0'
    #   NVIDIA_DRIVER_CAPABILITIES: "all"
    # runtime: nvidia
    # gpus: all
    network_mode: 'host'
    pid: 'host'
    ipc: 'host'
    # cap_add:
    #   - ALL
