/**:
  ros__parameters:
    channel_type: 'serial'
    serial_port: '/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_163eedcf9fd5ef11985b704b49d2c684-if00-port0'
    serial_baudrate: 460800
    frame_id: 'lidar_link'
    inverted: false
    angle_compensate: true