/nanobot_imu:
  ros__parameters:
    device: /dev/i2c-1
    address: 75 # 0x4B in decimal
    read_freq: 50.0
    publish_freq: 30.0
    frame_id: imu_link
    use_mag: false
    enable_dynamic_cal: true
    debug: false
